/* Static component styles compiled by StyleX. Null axis longhands preserve
 * caller padding/margin overrides. Grouped media negation retains exact
 * breakpoint edges. Reset custom properties preserve the existing CSS contract.
 * The original build emitted no legacy animate-in/out or bg-opacity utilities;
 * those no-op class names intentionally introduce no animation or opacity. */
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  appAdminDashboardPageStyle1: {
    padding: "calc(var(--spacing)*8)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  appAdminDashboardPageStyle2: {},
  appAdminDashboardPageStyle3: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  appAdminDashboardPageStyle4: {
    fontSize: "var(--text-3xl)",
    lineHeight: "var(--tw-leading,var(--text-3xl--line-height))",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
    "--tw-tracking": "var(--tracking-tight)",
    letterSpacing: "var(--tracking-tight)",
    "--tw-leading": null,
  },
  appAdminDashboardPageStyle5: {
    display: "flex",
    gap: "calc(var(--spacing)*2)",
  },
  appAdminDashboardPageStyle6: {
    marginRight: "calc(var(--spacing)*2)",
    height: "calc(var(--spacing)*4)",
    width: "calc(var(--spacing)*4)",
  },
  appAdminDashboardPageStyle8: {
    borderRadius: "calc(var(--radius) - 2px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
  },
  appAdminDashboardPageStyle9: {
    textAlign: "right",
  },
  appAdminDashboardPageStyle10: {
    paddingBlock: "calc(var(--spacing)*6)",
    textAlign: "center",
  },
  appAdminDashboardPageStyle12: {
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
  },
  appAdminDashboardPageStyle13: {
    listStyleType: "disc",
    paddingLeft: "calc(var(--spacing)*4)",
  },
  appAdminDashboardPageStyle14: {
    color: "var(--muted-foreground)",
  },
  appAdminDashboardPageStyle16: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "calc(var(--spacing)*2)",
  },
  appAdminDashboardPageStyle17: {
    height: "calc(var(--spacing)*4)",
    width: "calc(var(--spacing)*4)",
  },
  appAdminOrganizersAddPageStyle2: {
    marginInline: "auto",
    maxWidth: "var(--container-md)",
  },
  appAdminOrganizersAddPageStyle5: {},
  appAdminOrganizersAddPageStyle6: {},
  appAdminOrganizersPageStyle10: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "3.40282e+38px",
    backgroundColor: "var(--color-purple-100)",
    paddingInline: "calc(var(--spacing)*2)",
    paddingBlock: "calc(var(--spacing)*1)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    color: "var(--color-purple-800)",
    "--tw-leading": null,
  },
  appAdminOrganizersPageStyle11: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "3.40282e+38px",
    backgroundColor: "var(--color-blue-100)",
    paddingInline: "calc(var(--spacing)*2)",
    paddingBlock: "calc(var(--spacing)*1)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    color: "var(--color-blue-800)",
    "--tw-leading": null,
  },
  appAdminOrganizersPageStyle12: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "3.40282e+38px",
    backgroundColor: "var(--color-green-100)",
    paddingInline: "calc(var(--spacing)*2)",
    paddingBlock: "calc(var(--spacing)*1)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    color: "var(--color-green-800)",
    "--tw-leading": null,
  },
  appAdminParticipantsPageStyle1: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "3.40282e+38px",
    backgroundColor: "color-mix(in oklab,var(--primary)10%,transparent)",
    paddingInline: "calc(var(--spacing)*2)",
    paddingBlock: "calc(var(--spacing)*1)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    color: "var(--primary)",
    "--tw-leading": null,
  },
  appAdminParticipantsPageStyle5: {
    marginBottom: "calc(var(--spacing)*6)",
    display: "flex",
    gap: "calc(var(--spacing)*4)",
  },
  appAdminParticipantsPageStyle6: {
    position: "relative",
    flex: "1",
  },
  appAdminParticipantsPageStyle7: {
    position: "absolute",
    top: "calc(var(--spacing)*2.5)",
    left: "calc(var(--spacing)*2.5)",
    height: "calc(var(--spacing)*4)",
    width: "calc(var(--spacing)*4)",
    color: "var(--muted-foreground)",
  },
  appAdminParticipantsPageStyle8: {
    paddingLeft: "calc(var(--spacing)*8)",
  },
  appAdminParticipantsPageStyle9: {
    paddingBlock: "calc(var(--spacing)*8)",
    textAlign: "center",
  },
  appAdminRoomsPageStyle15: {
    display: "grid",
    gap: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*4)",
  },
  appAdminRoomsPageStyle16: {
    display: "grid",
    gap: "calc(var(--spacing)*2)",
  },
  appAdminTeamsIdPageStyle3: {
    display: "flex",
    alignItems: "center",
    gap: "calc(var(--spacing)*4)",
  },
  appAdminTeamsIdPageStyle7: {
    display: "grid",
    gap: "calc(var(--spacing)*6)",
    gridTemplateColumns: {
      default: null,
      "@media (width>=48rem)": "repeat(2,minmax(0,1fr))",
    },
  },
  appAdminTeamsIdPageStyle9: {
    display: "flex",
    flexDirection: "column",
  },
  appAdminTeamsIdPageStyle10: {
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    color: "var(--muted-foreground)",
    "--tw-leading": null,
  },
  appAdminTeamsIdPageStyle11: {
    fontSize: "var(--text-lg)",
    lineHeight: "var(--tw-leading,var(--text-lg--line-height))",
    "--tw-leading": null,
  },
  appAdminTeamsIdPageStyle25: {},
  appAdminTeamsIdPageStyle26: {
    display: "grid",
    gridTemplateColumns: "repeat(2,minmax(0,1fr))",
    gap: "calc(var(--spacing)*4)",
  },
  appAdminTeamsIdPageStyle28: {
    height: "200px",
    borderRadius: "calc(var(--radius) - 2px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    padding: "calc(var(--spacing)*2)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  appAdminTeamsIdPageStyle29: {},
  appAdminTeamsIdPageStyle30: {
    width: "100%",
    justifyContent: "flex-start",
    borderRadius: "calc(var(--radius) - 2px)",
  },
  appAdminTeamsIdPageStyle31: {
    textAlign: "center",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    color: "var(--muted-foreground)",
    "--tw-leading": null,
  },
  appAdminTeamsAddPageStyle2: {
    marginInline: "auto",
    maxWidth: "var(--container-4xl)",
  },
  appAdminTeamsAddPageStyle7: {
    position: "relative",
    marginBottom: "calc(var(--spacing)*8)",
    borderRadius: "var(--radius)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    padding: "calc(var(--spacing)*4)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  appAdminTeamsAddPageStyle8: {
    marginBottom: "calc(var(--spacing)*4)",
    display: "grid",
    gap: "calc(var(--spacing)*4)",
  },
  appAdminTeamsAddPageStyle12: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(1,minmax(0,1fr))",
      "@media (width>=48rem)": "repeat(2,minmax(0,1fr))",
    },
    gap: "calc(var(--spacing)*4)",
  },
  appAdminTeamsAddPageStyle13: {
    width: "100%",
  },
  appLayoutStyle1: {
    WebkitFontSmoothing: "antialiased",
    MozOsxFontSmoothing: "grayscale",
  },
  appLoginPageStyle1: {
    display: "flex",
    minHeight: "100svh",
    width: "100%",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: {
      default: "calc(var(--spacing)*6)",
      "@media (width>=48rem)": "calc(var(--spacing)*10)",
    },
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  appLoginPageStyle2: {
    width: "100%",
    maxWidth: "var(--container-sm)",
  },
  appLoginPageStyle3: {
    marginBottom: "calc(var(--spacing)*6)",
    borderColor: "var(--color-green-500)",
    backgroundColor: "var(--color-green-50)",
  },
  appLoginPageStyle4: {
    height: "calc(var(--spacing)*4)",
    width: "calc(var(--spacing)*4)",
    color: "var(--color-green-600)",
  },
  appLoginPageStyle5: {
    marginBottom: "calc(var(--spacing)*6)",
    borderColor: "var(--destructive)",
    backgroundColor: "color-mix(in oklab,var(--destructive)10%,transparent)",
  },
  appLoginPageStyle6: {
    height: "calc(var(--spacing)*4)",
    width: "calc(var(--spacing)*4)",
    color: "var(--destructive)",
  },
  appPageStyle1: {
    display: "grid",
    minHeight: "100vh",
    gridTemplateRows: "20px 1fr 20px",
    alignItems: "center",
    justifyItems: "center",
    gap: "calc(var(--spacing)*16)",
    padding: {
      default: "calc(var(--spacing)*8)",
      "@media (width>=40rem)": "calc(var(--spacing)*20)",
    },
    paddingBottom: "calc(var(--spacing)*20)",
    fontFamily: "var(--font-geist-sans)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  appPageStyle2: {
    gridRowStart: "2",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "32px",
  },
  appPageStyle3: {
    textAlign: "center",
    fontSize: "var(--text-3xl)",
    lineHeight: "var(--tw-leading,var(--text-3xl--line-height))",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
    "--tw-leading": null,
  },
  componentsDashboardLayoutStyle1: {
    display: "flex",
    height: "100vh",
  },
  componentsDashboardLayoutStyle2: {
    display: {
      default: "none",
      "@media (width>=48rem)": "block",
    },
    width: "calc(var(--spacing)*64)",
    borderRightStyle: "var(--tw-border-style)",
    borderRightWidth: "1px",
    borderColor: "var(--sidebar-border)",
    backgroundColor: "var(--sidebar)",
    padding: "calc(var(--spacing)*4)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsDashboardLayoutStyle3: {
    marginBottom: "calc(var(--spacing)*8)",
    display: "flex",
    alignItems: "center",
    gap: "calc(var(--spacing)*2)",
    paddingInline: "calc(var(--spacing)*2)",
  },
  componentsDashboardLayoutStyle4: {
    display: "flex",
    height: "calc(var(--spacing)*8)",
    width: "calc(var(--spacing)*8)",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "3.40282e+38px",
    backgroundColor: "var(--sidebar-primary)",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
    color: "var(--color-white)",
  },
  componentsDashboardLayoutStyle5: {
    fontSize: "var(--text-xl)",
    lineHeight: "var(--tw-leading,var(--text-xl--line-height))",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
    color: "var(--sidebar-foreground)",
    "--tw-leading": null,
  },
  componentsDashboardLayoutStyle7: {
    width: "100%",
    justifyContent: "flex-start",
  },
  componentsDashboardLayoutStyle8: {
    marginRight: "calc(var(--spacing)*2)",
    height: "calc(var(--spacing)*5)",
    width: "calc(var(--spacing)*5)",
  },
  componentsDashboardLayoutStyle20: {
    width: "100%",
    justifyContent: "flex-start",
    color: "var(--destructive)",
  },
  componentsDashboardLayoutStyle22: {
    position: "fixed",
    top: "calc(var(--spacing)*4)",
    left: "calc(var(--spacing)*4)",
    zIndex: "50",
    display: {
      default: null,
      "@media (width>=48rem)": "none",
    },
  },
  componentsDashboardLayoutStyle23: {
    height: "calc(var(--spacing)*6)",
    width: "calc(var(--spacing)*6)",
  },
  componentsDashboardLayoutStyle24: {
    position: "fixed",
    inset: "calc(var(--spacing)*0)",
    zIndex: "40",
    backgroundColor: "var(--color-black)",
    display: {
      default: null,
      "@media (width>=48rem)": "none",
    },
  },
  componentsDashboardLayoutStyle25: {
    height: "100%",
    width: "calc(var(--spacing)*64)",
    backgroundColor: "var(--sidebar)",
    padding: "calc(var(--spacing)*4)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsDashboardLayoutStyle26: {
    marginBottom: "calc(var(--spacing)*8)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  componentsDashboardLayoutStyle45: {
    flex: "1",
    overflow: "auto",
  },
  componentsDashboardLayoutStyle46: {
    position: "sticky",
    top: "calc(var(--spacing)*0)",
    zIndex: "10",
    borderBottomStyle: "var(--tw-border-style)",
    borderBottomWidth: "1px",
    backgroundColor: "var(--card)",
    padding: "calc(var(--spacing)*4)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsDashboardLayoutStyle48: {
    fontSize: "var(--text-xl)",
    lineHeight: "var(--tw-leading,var(--text-xl--line-height))",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
    "--tw-leading": null,
  },
  componentsDashboardLayoutStyle49: {
    display: "flex",
    alignItems: "center",
    gap: "calc(var(--spacing)*2)",
  },
  componentsDashboardLayoutStyle50: {
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    color: "var(--muted-foreground)",
    "--tw-leading": null,
  },
  componentsDashboardLayoutStyle51: {
    display: "flex",
    height: "calc(var(--spacing)*8)",
    width: "calc(var(--spacing)*8)",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "3.40282e+38px",
    backgroundColor: "var(--secondary)",
  },
  componentsDashboardLayoutStyle52: {
    padding: "calc(var(--spacing)*6)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsDashboardStatsStyle1: {
    display: "grid",
    gap: "calc(var(--spacing)*4)",
    gridTemplateColumns: {
      default: null,
      "@media (width>=48rem)": "repeat(2,minmax(0,1fr))",
      "@media (width>=64rem)": "repeat(3,minmax(0,1fr))",
    },
  },
  componentsDashboardStatsStyle2: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: "calc(var(--spacing)*2)",
  },
  componentsDashboardStatsStyle3: {
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    "--tw-leading": null,
  },
  componentsDashboardStatsStyle4: {
    height: "calc(var(--spacing)*4)",
    width: "calc(var(--spacing)*4)",
    color: "var(--muted-foreground)",
  },
  componentsDashboardStatsStyle5: {
    fontSize: "var(--text-2xl)",
    lineHeight: "var(--tw-leading,var(--text-2xl--line-height))",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
    "--tw-leading": null,
  },
  componentsDashboardStatsStyle6: {
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    color: "var(--muted-foreground)",
    "--tw-leading": null,
  },
  componentsDataTableStyle1: {
    display: "flex",
    alignItems: "center",
    paddingBlock: "calc(var(--spacing)*4)",
  },
  componentsDataTableStyle2: {
    maxWidth: "var(--container-sm)",
  },
  componentsDataTableStyle4: {
    height: "calc(var(--spacing)*24)",
    textAlign: "center",
  },
  componentsDataTableStyle5: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBlock: "calc(var(--spacing)*4)",
  },
  componentsLoginFormStyle1: {
    display: "flex",
    flexDirection: "column",
    gap: "calc(var(--spacing)*6)",
  },
  componentsLoginFormStyle2: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "calc(var(--spacing)*2)",
    textAlign: "center",
  },
  componentsLoginFormStyle4: {
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    textWrap: "balance",
    color: "var(--muted-foreground)",
    "--tw-leading": null,
  },
  componentsLoginFormStyle5: {
    display: "grid",
    gap: "calc(var(--spacing)*6)",
  },
  componentsLoginFormStyle6: {
    display: "grid",
    gap: "calc(var(--spacing)*3)",
  },
  componentsLoginFormStyle8: {
    display: "flex",
    alignItems: "center",
  },
  componentsLoginFormStyle9: {
    marginLeft: "auto",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    textUnderlineOffset: "4px",
    "--tw-leading": null,
  },
  componentsLoginFormStyle11: {
    marginRight: "calc(var(--spacing)*2)",
    height: "calc(var(--spacing)*4)",
    width: "calc(var(--spacing)*4)",
    // The original --animate-spin token is the shorthand "spin 1s linear infinite".
    animationName: "spin",
    animationDuration: "1s",
    animationTimingFunction: "linear",
    animationDelay: "0s",
    animationIterationCount: "infinite",
    animationDirection: "normal",
    animationFillMode: "none",
  },
  alertvariantdefault: {
    position: "relative",
    display: "grid",
    width: "100%",
    gridTemplateColumns: "0 1fr",
    alignItems: "flex-start",
    rowGap: "calc(var(--spacing)*.5)",
    borderRadius: "var(--radius)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--card)",
    paddingInline: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*3)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    color: "var(--card-foreground)",
    "--tw-leading": null,
  },
  alertvariantdestructive: {
    position: "relative",
    display: "grid",
    width: "100%",
    gridTemplateColumns: "0 1fr",
    alignItems: "flex-start",
    rowGap: "calc(var(--spacing)*.5)",
    borderRadius: "var(--radius)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--card)",
    paddingInline: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*3)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    color: "var(--destructive)",
    "--tw-leading": null,
  },
  alertBase: {
    position: "relative",
    display: "grid",
    width: "100%",
    gridTemplateColumns: "0 1fr",
    alignItems: "flex-start",
    rowGap: "calc(var(--spacing)*.5)",
    borderRadius: "var(--radius)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    paddingInline: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*3)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-leading": null,
  },
  componentsUiAlertStyle1: {
    gridColumnStart: "2",
    WebkitLineClamp: "1",
    WebkitBoxOrient: "vertical",
    display: "-webkit-box",
    overflow: "hidden",
    minHeight: "calc(var(--spacing)*4)",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    "--tw-tracking": "var(--tracking-tight)",
    letterSpacing: "var(--tracking-tight)",
  },
  componentsUiAlertStyle2: {
    gridColumnStart: "2",
    display: "grid",
    justifyItems: "start",
    gap: "calc(var(--spacing)*1)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    color: "var(--muted-foreground)",
    "--tw-leading": null,
  },
  buttonvariantdefault: {
    display: "inline-flex",
    flexShrink: "0",
    alignItems: "center",
    justifyContent: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 2px)",
    backgroundColor: "var(--primary)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    whiteSpace: "nowrap",
    color: "var(--primary-foreground)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-shadow": "0 1px 2px 0 var(--tw-shadow-color,#0000000d)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    "--tw-leading": null,
  },
  buttonvariantdestructive: {
    display: "inline-flex",
    flexShrink: "0",
    alignItems: "center",
    justifyContent: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 2px)",
    backgroundColor: "var(--destructive)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    whiteSpace: "nowrap",
    color: "var(--color-white)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-shadow": "0 1px 2px 0 var(--tw-shadow-color,#0000000d)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    "--tw-leading": null,
  },
  buttonvariantoutline: {
    display: "inline-flex",
    flexShrink: "0",
    alignItems: "center",
    justifyContent: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 2px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--background)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    whiteSpace: "nowrap",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-shadow": "0 1px 2px 0 var(--tw-shadow-color,#0000000d)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    "--tw-leading": null,
  },
  buttonvariantsecondary: {
    display: "inline-flex",
    flexShrink: "0",
    alignItems: "center",
    justifyContent: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 2px)",
    backgroundColor: "var(--secondary)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    whiteSpace: "nowrap",
    color: "var(--secondary-foreground)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-shadow": "0 1px 2px 0 var(--tw-shadow-color,#0000000d)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    "--tw-leading": null,
  },
  buttonvariantghost: {
    display: "inline-flex",
    flexShrink: "0",
    alignItems: "center",
    justifyContent: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 2px)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    whiteSpace: "nowrap",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    "--tw-leading": null,
  },
  buttonvariantlink: {
    display: "inline-flex",
    flexShrink: "0",
    alignItems: "center",
    justifyContent: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 2px)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    whiteSpace: "nowrap",
    color: "var(--primary)",
    textUnderlineOffset: "4px",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    "--tw-leading": null,
  },
  buttonsizedefault: {
    height: "calc(var(--spacing)*9)",
    paddingInline: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*2)",
  },
  buttonsizesm: {
    height: "calc(var(--spacing)*8)",
    gap: "calc(var(--spacing)*1.5)",
    borderRadius: "calc(var(--radius) - 2px)",
    paddingInline: "calc(var(--spacing)*3)",
  },
  buttonsizelg: {
    height: "calc(var(--spacing)*10)",
    borderRadius: "calc(var(--radius) - 2px)",
    paddingInline: "calc(var(--spacing)*6)",
  },
  buttonsizeicon: {
    width: "calc(var(--spacing)*9)",
    height: "calc(var(--spacing)*9)",
  },
  buttonBase: {
    display: "inline-flex",
    flexShrink: "0",
    alignItems: "center",
    justifyContent: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 2px)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    whiteSpace: "nowrap",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    "--tw-leading": null,
  },
  componentsUiCardStyle1: {
    display: "flex",
    flexDirection: "column",
    gap: "calc(var(--spacing)*6)",
    borderRadius: "calc(var(--radius) + 4px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--card)",
    paddingBlock: "calc(var(--spacing)*6)",
    color: "var(--card-foreground)",
    "--tw-shadow":
      "0 1px 3px 0 var(--tw-shadow-color,#0000001a),0 1px 2px -1px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
  },
  componentsUiCardStyle2: {
    container: "card-header/inline-size",
    display: "grid",
    gridAutoRows: "min-content",
    gridTemplateRows: "auto auto",
    alignItems: "flex-start",
    gap: "calc(var(--spacing)*1.5)",
    paddingInline: "calc(var(--spacing)*6)",
  },
  componentsUiCardStyle3: {
    "--tw-leading": "1",
    lineHeight: "1",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
  },
  componentsUiCardStyle5: {
    gridColumnStart: "2",
    gridRow: "span 2/span 2",
    gridRowStart: "1",
    alignSelf: "flex-start",
    justifySelf: "flex-end",
  },
  componentsUiCardStyle6: {
    paddingInline: "calc(var(--spacing)*6)",
  },
  componentsUiCardStyle7: {
    display: "flex",
    alignItems: "center",
    paddingInline: "calc(var(--spacing)*6)",
  },
  componentsUiCommandStyle1: {
    display: "flex",
    height: "100%",
    width: "100%",
    flexDirection: "column",
    overflow: "hidden",
    borderRadius: "calc(var(--radius) - 2px)",
    backgroundColor: "var(--popover)",
    color: "var(--popover-foreground)",
  },
  componentsUiCommandStyle2: {
    clip: "rect(0,0,0,0)",
    whiteSpace: "nowrap",
    borderWidth: "0",
    width: "1px",
    height: "1px",
    margin: "-1px",
    padding: "0",
    overflow: "hidden",
    position: "absolute",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
    marginInline: null,
    marginBlock: null,
    marginTop: null,
    marginRight: null,
    marginBottom: null,
    marginLeft: null,
    marginInlineStart: null,
    marginInlineEnd: null,
    marginBlockStart: null,
    marginBlockEnd: null,
  },
  componentsUiCommandStyle3: {
    overflow: "hidden",
    padding: "calc(var(--spacing)*0)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsUiCommandStyle4: {},
  componentsUiCommandStyle5: {
    display: "flex",
    height: "calc(var(--spacing)*9)",
    alignItems: "center",
    gap: "calc(var(--spacing)*2)",
    borderBottomStyle: "var(--tw-border-style)",
    borderBottomWidth: "1px",
    paddingInline: "calc(var(--spacing)*3)",
  },
  componentsUiCommandStyle6: {
    width: "calc(var(--spacing)*4)",
    height: "calc(var(--spacing)*4)",
    flexShrink: "0",
    opacity: ".5",
  },
  componentsUiCommandStyle7: {
    display: "flex",
    height: "calc(var(--spacing)*10)",
    width: "100%",
    borderRadius: "calc(var(--radius) - 2px)",
    backgroundColor: "#0000",
    paddingBlock: "calc(var(--spacing)*3)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    outlineOffset: {
      default: null,
      "@media (forced-colors:active)": "2px",
    },
    outline: {
      default: null,
      "@media (forced-colors:active)": "2px solid #0000",
    },
    "--tw-leading": null,
  },
  componentsUiCommandStyle8: {
    maxHeight: "300px",
    scrollPaddingBlock: "calc(var(--spacing)*1)",
    overflowX: "hidden",
    overflowY: "auto",
  },
  componentsUiCommandStyle9: {
    paddingBlock: "calc(var(--spacing)*6)",
    textAlign: "center",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-leading": null,
  },
  componentsUiCommandStyle10: {
    overflow: "hidden",
    padding: "calc(var(--spacing)*1)",
    color: "var(--foreground)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsUiCommandStyle11: {
    marginInline: "calc(var(--spacing)*-1)",
    height: "1px",
    backgroundColor: "var(--border)",
  },
  componentsUiCommandStyle12: {
    position: "relative",
    display: "flex",
    cursor: "default",
    alignItems: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 4px)",
    paddingInline: "calc(var(--spacing)*2)",
    paddingBlock: "calc(var(--spacing)*1.5)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    outlineOffset: {
      default: null,
      "@media (forced-colors:active)": "2px",
    },
    outline: {
      default: null,
      "@media (forced-colors:active)": "2px solid #0000",
    },
    WebkitUserSelect: "none",
    userSelect: "none",
    "--tw-leading": null,
  },
  componentsUiCommandStyle13: {
    marginLeft: "auto",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    "--tw-tracking": "var(--tracking-widest)",
    letterSpacing: "var(--tracking-widest)",
    color: "var(--muted-foreground)",
    "--tw-leading": null,
  },
  componentsUiDialogStyle1: {
    position: "fixed",
    inset: "calc(var(--spacing)*0)",
    zIndex: "50",
    backgroundColor: "color-mix(in oklab,var(--color-black)50%,transparent)",
  },
  componentsUiDialogStyle2: {
    position: "fixed",
    top: "50%",
    left: "50%",
    zIndex: "50",
    display: "grid",
    width: "100%",
    maxWidth: {
      default: "calc(100% - 2rem)",
      "@media (width>=40rem)": "var(--container-lg)",
    },
    "--tw-translate-x": "-50%",
    translate: "var(--tw-translate-x)var(--tw-translate-y)",
    "--tw-translate-y": "-50%",
    gap: "calc(var(--spacing)*4)",
    borderRadius: "var(--radius)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--background)",
    padding: "calc(var(--spacing)*6)",
    "--tw-shadow":
      "0 10px 15px -3px var(--tw-shadow-color,#0000001a),0 4px 6px -4px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-duration": ".2s",
    transitionDuration: ".2s",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsUiDialogStyle3: {
    position: "absolute",
    top: "calc(var(--spacing)*4)",
    right: "calc(var(--spacing)*4)",
    borderRadius: "var(--radius-xs)",
    opacity: ".7",
    "--tw-ring-offset-color": "var(--background)",
    transitionProperty: "opacity",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  componentsUiDialogStyle5: {
    display: "flex",
    flexDirection: "column",
    gap: "calc(var(--spacing)*2)",
    textAlign: {
      default: "center",
      "@media (width>=40rem)": "left",
    },
  },
  componentsUiDialogStyle6: {
    display: "flex",
    flexDirection: {
      default: "column-reverse",
      "@media (width>=40rem)": "row",
    },
    gap: "calc(var(--spacing)*2)",
    justifyContent: {
      default: null,
      "@media (width>=40rem)": "flex-end",
    },
  },
  componentsUiDialogStyle7: {
    fontSize: "var(--text-lg)",
    lineHeight: "1",
    "--tw-leading": "1",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
  },
  componentsUiDropdownMenuStyle1: {
    zIndex: "50",
    maxHeight: "var(--radix-dropdown-menu-content-available-height)",
    minWidth: "8rem",
    overflowX: "hidden",
    overflowY: "auto",
    borderRadius: "calc(var(--radius) - 2px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--popover)",
    padding: "calc(var(--spacing)*1)",
    color: "var(--popover-foreground)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-shadow":
      "0 4px 6px -1px var(--tw-shadow-color,#0000001a),0 2px 4px -2px var(--tw-shadow-color,#0000001a)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsUiDropdownMenuStyle2: {
    position: "relative",
    display: "flex",
    cursor: "default",
    alignItems: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 4px)",
    paddingInline: "calc(var(--spacing)*2)",
    paddingBlock: "calc(var(--spacing)*1.5)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    outlineOffset: {
      default: null,
      "@media (forced-colors:active)": "2px",
    },
    outline: {
      default: null,
      "@media (forced-colors:active)": "2px solid #0000",
    },
    WebkitUserSelect: "none",
    userSelect: "none",
    "--tw-leading": null,
  },
  componentsUiDropdownMenuStyle3: {
    position: "relative",
    display: "flex",
    cursor: "default",
    alignItems: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 4px)",
    paddingBlock: "calc(var(--spacing)*1.5)",
    paddingRight: "calc(var(--spacing)*2)",
    paddingLeft: "calc(var(--spacing)*8)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    outlineOffset: {
      default: null,
      "@media (forced-colors:active)": "2px",
    },
    outline: {
      default: null,
      "@media (forced-colors:active)": "2px solid #0000",
    },
    WebkitUserSelect: "none",
    userSelect: "none",
    "--tw-leading": null,
  },
  componentsUiDropdownMenuStyle4: {
    pointerEvents: "none",
    position: "absolute",
    left: "calc(var(--spacing)*2)",
    display: "flex",
    width: "calc(var(--spacing)*3.5)",
    height: "calc(var(--spacing)*3.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  componentsUiDropdownMenuStyle5: {
    width: "calc(var(--spacing)*4)",
    height: "calc(var(--spacing)*4)",
  },
  componentsUiDropdownMenuStyle8: {
    width: "calc(var(--spacing)*2)",
    height: "calc(var(--spacing)*2)",
    fill: "currentColor",
  },
  componentsUiDropdownMenuStyle9: {
    paddingInline: "calc(var(--spacing)*2)",
    paddingBlock: "calc(var(--spacing)*1.5)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    "--tw-leading": null,
  },
  componentsUiDropdownMenuStyle10: {
    marginInline: "calc(var(--spacing)*-1)",
    marginBlock: "calc(var(--spacing)*1)",
    height: "1px",
    backgroundColor: "var(--border)",
  },
  componentsUiDropdownMenuStyle12: {
    display: "flex",
    cursor: "default",
    alignItems: "center",
    borderRadius: "calc(var(--radius) - 4px)",
    paddingInline: "calc(var(--spacing)*2)",
    paddingBlock: "calc(var(--spacing)*1.5)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    outlineOffset: {
      default: null,
      "@media (forced-colors:active)": "2px",
    },
    outline: {
      default: null,
      "@media (forced-colors:active)": "2px solid #0000",
    },
    WebkitUserSelect: "none",
    userSelect: "none",
    "--tw-leading": null,
  },
  componentsUiDropdownMenuStyle13: {
    marginLeft: "auto",
    width: "calc(var(--spacing)*4)",
    height: "calc(var(--spacing)*4)",
  },
  componentsUiDropdownMenuStyle14: {
    zIndex: "50",
    minWidth: "8rem",
    overflow: "hidden",
    borderRadius: "calc(var(--radius) - 2px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--popover)",
    padding: "calc(var(--spacing)*1)",
    color: "var(--popover-foreground)",
    "--tw-shadow":
      "0 10px 15px -3px var(--tw-shadow-color,#0000001a),0 4px 6px -4px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsUiFormStyle2: {},
  componentsUiFormStyle4: {
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    color: "var(--destructive)",
    "--tw-leading": null,
  },
  componentsUiInputStyle1: {
    display: "flex",
    height: "calc(var(--spacing)*9)",
    width: "100%",
    minWidth: "calc(var(--spacing)*0)",
    borderRadius: "calc(var(--radius) - 2px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "var(--input)",
    backgroundColor: "#0000",
    paddingInline: "calc(var(--spacing)*3)",
    paddingBlock: "calc(var(--spacing)*1)",
    fontSize: {
      default: "var(--text-base)",
      "@media (width>=48rem)": "var(--text-sm)",
    },
    lineHeight: {
      default: "var(--tw-leading,var(--text-base--line-height))",
      "@media (width>=48rem)": "var(--tw-leading,var(--text-sm--line-height))",
    },
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-shadow": "0 1px 2px 0 var(--tw-shadow-color,#0000000d)",
    transitionProperty: "color,box-shadow",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    "--tw-leading": null,
  },
  componentsUiLabelStyle1: {
    display: "flex",
    alignItems: "center",
    gap: "calc(var(--spacing)*2)",
    fontSize: "var(--text-sm)",
    lineHeight: "1",
    "--tw-leading": "1",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    WebkitUserSelect: "none",
    userSelect: "none",
  },
  scrollVertical: {
    display: "flex",
    height: "100%",
    width: "calc(var(--spacing)*2.5)",
    touchAction: "none",
    borderLeftStyle: "var(--tw-border-style)",
    borderLeftWidth: "1px",
    borderLeftColor: "#0000",
    padding: "1px",
    transitionProperty:
      "color,background-color,border-color,outline-color,text-decoration-color,fill,stroke,--tw-gradient-from,--tw-gradient-via,--tw-gradient-to",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    WebkitUserSelect: "none",
    userSelect: "none",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  scrollHorizontal: {
    display: "flex",
    height: "calc(var(--spacing)*2.5)",
    touchAction: "none",
    flexDirection: "column",
    borderTopStyle: "var(--tw-border-style)",
    borderTopWidth: "1px",
    borderTopColor: "#0000",
    padding: "1px",
    transitionProperty:
      "color,background-color,border-color,outline-color,text-decoration-color,fill,stroke,--tw-gradient-from,--tw-gradient-via,--tw-gradient-to",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    WebkitUserSelect: "none",
    userSelect: "none",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsUiScrollAreaStyle1: {
    position: "relative",
  },
  componentsUiScrollAreaStyle2: {
    width: "100%",
    height: "100%",
    borderRadius: "inherit",
    "--tw-ring-color": "color-mix(in oklab,var(--ring)10%,transparent)",
    outlineColor: "color-mix(in oklab,var(--ring)50%,transparent)",
    transitionProperty: "color,box-shadow",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  componentsUiScrollAreaStyle3: {
    position: "relative",
    flex: "1",
    borderRadius: "3.40282e+38px",
    backgroundColor: "var(--border)",
  },
  componentsUiSelectStyle1: {
    position: "relative",
    zIndex: "50",
    maxHeight: "var(--radix-select-content-available-height)",
    minWidth: "8rem",
    overflowX: "hidden",
    overflowY: "auto",
    borderRadius: "calc(var(--radius) - 2px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--popover)",
    color: "var(--popover-foreground)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-shadow":
      "0 4px 6px -1px var(--tw-shadow-color,#0000001a),0 2px 4px -2px var(--tw-shadow-color,#0000001a)",
  },
  componentsUiSelectStyle2: {
    position: "relative",
    zIndex: "50",
    maxHeight: "var(--radix-select-content-available-height)",
    minWidth: "8rem",
    overflowX: "hidden",
    overflowY: "auto",
    borderRadius: "calc(var(--radius) - 2px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--popover)",
    color: "var(--popover-foreground)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-shadow":
      "0 4px 6px -1px var(--tw-shadow-color,#0000001a),0 2px 4px -2px var(--tw-shadow-color,#0000001a)",
  },
  componentsUiSelectStyle3: {
    height: "var(--radix-select-trigger-height)",
    width: "100%",
    minWidth: "var(--radix-select-trigger-width)",
    scrollMarginBlock: "calc(var(--spacing)*1)",
    padding: "calc(var(--spacing)*1)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsUiSelectStyle4: {
    padding: "calc(var(--spacing)*1)",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsUiSelectStyle5: {
    display: "flex",
    width: "fit-content",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 2px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "var(--input)",
    backgroundColor: "#0000",
    paddingInline: "calc(var(--spacing)*3)",
    paddingBlock: "calc(var(--spacing)*2)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    whiteSpace: "nowrap",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-shadow": "0 1px 2px 0 var(--tw-shadow-color,#0000000d)",
    transitionProperty: "color,box-shadow",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    "--tw-leading": null,
  },
  componentsUiSelectStyle6: {
    width: "calc(var(--spacing)*4)",
    height: "calc(var(--spacing)*4)",
    opacity: ".5",
  },
  componentsUiSelectStyle7: {
    paddingInline: "calc(var(--spacing)*2)",
    paddingBlock: "calc(var(--spacing)*1.5)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    "--tw-leading": null,
  },
  componentsUiSelectStyle8: {
    position: "relative",
    display: "flex",
    width: "100%",
    cursor: "default",
    alignItems: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 4px)",
    paddingBlock: "calc(var(--spacing)*1.5)",
    paddingRight: "calc(var(--spacing)*8)",
    paddingLeft: "calc(var(--spacing)*2)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    outlineOffset: {
      default: null,
      "@media (forced-colors:active)": "2px",
    },
    outline: {
      default: null,
      "@media (forced-colors:active)": "2px solid #0000",
    },
    WebkitUserSelect: "none",
    userSelect: "none",
    "--tw-leading": null,
  },
  componentsUiSelectStyle9: {
    position: "absolute",
    right: "calc(var(--spacing)*2)",
    display: "flex",
    width: "calc(var(--spacing)*3.5)",
    height: "calc(var(--spacing)*3.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  componentsUiSelectStyle11: {
    pointerEvents: "none",
    marginInline: "calc(var(--spacing)*-1)",
    marginBlock: "calc(var(--spacing)*1)",
    height: "1px",
    backgroundColor: "var(--border)",
  },
  componentsUiSelectStyle12: {
    display: "flex",
    cursor: "default",
    alignItems: "center",
    justifyContent: "center",
    paddingBlock: "calc(var(--spacing)*1)",
  },
  componentsUiSwitchStyle1: {
    display: "inline-flex",
    height: "1.15rem",
    width: "calc(var(--spacing)*8)",
    flexShrink: "0",
    alignItems: "center",
    borderRadius: "3.40282e+38px",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "#0000",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-shadow": "0 1px 2px 0 var(--tw-shadow-color,#0000000d)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
  },
  componentsUiSwitchStyle2: {
    pointerEvents: "none",
    display: "block",
    width: "calc(var(--spacing)*4)",
    height: "calc(var(--spacing)*4)",
    borderRadius: "3.40282e+38px",
    backgroundColor: "var(--background)",
    "--tw-ring-shadow":
      "var(--tw-ring-inset,)0 0 0 calc(0px + var(--tw-ring-offset-width))var(--tw-ring-color,currentColor)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    transitionProperty: "transform,translate,scale,rotate",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  componentsUiTableStyle1: {
    position: "relative",
    width: "100%",
    overflowX: "auto",
  },
  componentsUiTableStyle2: {
    width: "100%",
    captionSide: "bottom",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-leading": null,
  },
  componentsUiTableStyle3: {},
  componentsUiTableStyle4: {},
  componentsUiTableStyle5: {
    borderTopStyle: "var(--tw-border-style)",
    borderTopWidth: "1px",
    backgroundColor: "color-mix(in oklab,var(--muted)50%,transparent)",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
  },
  componentsUiTableStyle6: {
    borderBottomStyle: "var(--tw-border-style)",
    borderBottomWidth: "1px",
    transitionProperty:
      "color,background-color,border-color,outline-color,text-decoration-color,fill,stroke,--tw-gradient-from,--tw-gradient-via,--tw-gradient-to",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  componentsUiTableStyle7: {
    height: "calc(var(--spacing)*10)",
    paddingInline: "calc(var(--spacing)*2)",
    textAlign: "left",
    verticalAlign: "middle",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    whiteSpace: "nowrap",
    color: "var(--muted-foreground)",
  },
  componentsUiTableStyle8: {
    padding: "calc(var(--spacing)*2)",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
    paddingInline: null,
    paddingBlock: null,
    paddingTop: null,
    paddingRight: null,
    paddingBottom: null,
    paddingLeft: null,
    paddingInlineStart: null,
    paddingInlineEnd: null,
    paddingBlockStart: null,
    paddingBlockEnd: null,
  },
  componentsUiTableStyle9: {
    marginTop: "calc(var(--spacing)*4)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    color: "var(--muted-foreground)",
    "--tw-leading": null,
  },
});
